on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        shell: pwsh
        run: |
          Push-Location src
          $version = (nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
          Write-Host "Version $version"
          Pop-Location

          $packageUrl = "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}".ToLower()

          $archs = "amd64", "arm64v8"
          foreach ($arch in $archs) {
            docker build -t "$($packageUrl):latest-$($arch)" --build-arg ARCH=$($arch) .
            docker tag "$($packageUrl):latest-$($arch)" "$($packageUrl):$($version)-$($arch)"
            docker push "$($packageUrl):latest-$($arch)"
            docker push "$($packageUrl):$($version)-$($arch)"
          }

          docker manifest create `
                "$($packageUrl):latest" `
                --amend "$($packageUrl):latest-amd64" `
                --amend "$($packageUrl):latest-arm64v8"
          docker manifest create `
                "$($packageUrl):$($version)" `
                --amend "$($packageUrl):$($version)-amd64" `
                --amend "$($packageUrl):$($version)-arm64v8"
          docker manifest push "$($packageUrl):latest"
          docker manifest push "$($packageUrl):$($version)"
