on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64v8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        shell: pwsh
        run: |
          Push-Location src
          $version = (nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
          Write-Host "Version $version"
          Pop-Location

          $packageUrl = "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}".ToLower()

          docker buildx build -t "$($packageUrl):latest-${{ matrix.architecture }}" --build-arg ARCH=${{ matrix.architecture }} --cache-from="$($packageUrl):builder-${{ matrix.architecture }}" .
          docker tag "$($packageUrl):latest-${{ matrix.architecture }}" "$($packageUrl):$($version)-${{ matrix.architecture }}"
          docker push "$($packageUrl):latest-${{ matrix.architecture }}"
          docker push "$($packageUrl):$($version)-${{ matrix.architecture }}"
  push-manifest:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build manifest
        shell: pwsh
        run: |
          Push-Location src
          $version = (nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
          Write-Host "Version $version"
          Pop-Location

          $packageUrl = "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}".ToLower()

          docker manifest create `
                "$($packageUrl):latest" `
                --amend "$($packageUrl):latest-amd64" `
                --amend "$($packageUrl):latest-arm64v8"
          docker manifest create `
                "$($packageUrl):$($version)" `
                --amend "$($packageUrl):$($version)-amd64" `
                --amend "$($packageUrl):$($version)-arm64v8"
          docker manifest push "$($packageUrl):latest"
          docker manifest push "$($packageUrl):$($version)"
